import { Nav } from "@/components/nav"
import { Footer } from "@/components/footer"

export const metadata = {
  title: "Terms of Service",
  description: "Ollie terms of service. Read our usage rules and disclaimers.",
  alternates: { canonical: "/terms" },
}

export default function TermsPage() {
  return (
    <main className="relative min-h-screen bg-black">
      <Nav />
      <div className="max-w-3xl mx-auto px-6 pt-32 pb-20">
        <h1 className="text-4xl font-black text-white mb-2 tracking-tight">Terms of Service</h1>
        <p className="text-white/30 text-sm mb-12">Last updated: September 2026</p>

        <div className="prose prose-invert max-w-none space-y-10 text-white/60 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Ollie (&quot;the Service&quot;), you agree to be bound by these Terms of Service and our <a href="/privacy" className="text-sky-400 hover:underline">Privacy Policy</a>. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>Ollie is an AI-powered tool for entertainment. You upload a photo and the Service returns a list of soccer players whose faces most closely resemble yours. Results are generated by machine learning and are approximate. They are not scientific, medical, or legally definitive assessments, and they are not a way to identify anyone.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Upload images of individuals without their consent</li>
              <li>Use the Service to harass, stalk, or identify private individuals</li>
              <li>Use the Service for surveillance, law enforcement, or facial recognition profiling</li>
              <li>Attempt to reverse-engineer, scrape, or overload the Service, or get around its search limits</li>
              <li>Upload illegal content, including child sexual abuse material</li>
              <li>Use the Service in any way that violates applicable laws</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Age Restriction</h2>
            <p>You must be at least 18 years old to use Ollie. By using the Service you confirm you meet this requirement.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Accounts and Search Limits</h2>
            <p>Some features need an account. You are responsible for keeping your login secure. Searches are limited: visitors without an account get a limited number of free searches, and accounts have their own limit. We may change these limits at any time, and we may suspend or close accounts that break these terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Your Photos</h2>
            <p>You keep all rights to the photos you upload. You give us permission to process them only to run your search, as described in the Privacy Policy. You confirm that you have the right to upload each photo and, if it shows someone else, that they have agreed to it.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Intellectual Property and Takedowns</h2>
            <p>The Ollie website, code, AI model, and design are owned by us. You may not reproduce, distribute, or create derivative works from them without written permission. The player photos and names used for matching come from publicly available sources on the web and remain the property of their respective owners. If you own or represent a player, or you own a photo we display, and you want it removed, email us at the address below and we will remove it promptly.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Disclaimer of Warranties</h2>
            <p>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. We do not warrant that results will be accurate, that the Service will be uninterrupted, or that it will be error-free. The model can perform differently depending on the photo, lighting, and the person, so results may be less accurate for some faces than for others. Similarity results are for entertainment only.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, Ollie and its creators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to loss of data or reputation.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Player and Club Disclaimer</h2>
            <p>Ollie is not affiliated with, endorsed by, or connected to any player, club, league, or agency. Player names and likenesses are used only to identify public figures for entertainment comparison.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Changes to Terms</h2>
            <p>We may change these terms at any time. Changes will be posted on this page with an updated date. Continued use after changes means you accept them.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Governing Law</h2>
            <p>These terms are governed by the laws of the Province of British Columbia and the federal laws of Canada that apply there. Any dispute about them will be handled by the courts of British Columbia, unless the law where you live gives you the right to bring a claim elsewhere.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">13. Contact</h2>
            <p>Questions about these terms, or a takedown request? Contact us at <a href="mailto:lbrad@student.ubc.ca" className="text-sky-400 hover:underline">lbrad@student.ubc.ca</a>.</p>
          </section>

        </div>
      </div>
      <Footer />
    </main>
  )
}
