import { Nav } from "@/components/nav"
import { Footer } from "@/components/footer"
import { BGPattern } from "@/components/bg-pattern"

export const metadata = {
  title: "Terms of Service",
  description: "The rules for using Ollie's celebrity look-alike search: age limit, acceptable use, photos, emails, credits and disclaimers.",
  alternates: { canonical: "/terms" },
}

const EMAIL = "support@ollie.ml"
const link = "text-(--ollie-cyan) underline underline-offset-2 hover:text-white"

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main id="main" className="relative min-h-screen bg-transparent">
        <BGPattern variant="grid" mask="fade-edges" fill="rgba(255,255,255,0.04)" size={32} className="fixed" />
        <div className="max-w-3xl mx-auto px-6 pt-32 pb-20">
          <h1 className="text-4xl font-black text-white mb-2 tracking-tight">Terms of Service</h1>
          <p className="text-white/60 text-sm mb-12">Last updated: September 23, 2026</p>

          <div className="prose prose-invert max-w-none space-y-10 text-white/60 leading-relaxed">

            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Ollie (&quot;the Service&quot;), you agree to be bound by these Terms of Service and our <a href="/privacy" className={link}>Privacy Policy</a>. When you create an account, we ask you to confirm this. If you do not agree, do not use the Service.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
              <p>Ollie is an AI-powered tool for entertainment. You upload a photo and the Service returns a list of well-known celebrities whose faces most closely resemble yours. Results are generated by machine learning and are approximate. They are not scientific, medical, or legally definitive assessments, and they are not a way to identify anyone.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-2">
                <li>Upload images of individuals without their consent</li>
                <li>Use the Service to harass, stalk, or identify private individuals</li>
                <li>Use the Service for surveillance, law enforcement, or facial recognition profiling</li>
                <li>Use your results to claim that a celebrity endorses you or anything else, or to impersonate anyone</li>
                <li>Attempt to reverse-engineer, scrape, or overload the Service, or get around its search limits</li>
                <li>Upload illegal content, including child sexual abuse material</li>
                <li>Use the Service in any way that violates applicable laws</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">4. Age Restriction</h2>
              <p>You must be at least 18 years old to use Ollie. By using the Service you confirm you meet this requirement.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">5. Accounts and Search Limits</h2>
              <p>Some features need an account. You are responsible for keeping your login secure. Searches are limited: visitors without an account get a limited number of free searches, and accounts have their own limit. We may change these limits at any time, and we may suspend or close accounts that break these terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">6. Your Photos</h2>
              <p>You keep all rights to the photos you upload. You give us permission to process them only to run your search, as described in the Privacy Policy. You confirm that you have the right to upload each photo and, if it shows someone else, that they have agreed to it.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">7. Emails</h2>
              <p>Joining our email list is optional. If you opt in when you sign up, we may send occasional emails about new Ollie features and updates. You can unsubscribe at any time using the link in any email or by contacting us. We may still send you messages you need to use your account, such as an email to confirm your address.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">8. Intellectual Property, Celebrity Photos and Takedowns</h2>
              <p>The Ollie website, code, AI model, and design are owned by us. You may not reproduce, distribute, or create derivative works from them without written permission.</p>
              <p className="mt-3">The celebrity photos we show come from <a href="https://commons.wikimedia.org/" target="_blank" rel="noopener noreferrer" className={link}>Wikimedia Commons</a>. They belong to their photographers and are used, cropped, under the free licenses shown with each photo (such as public domain, CC0, CC BY and CC BY-SA). If you reuse one of these photos, the terms of its own license apply to you, not these terms. Celebrity names and likenesses are used only to identify public figures for entertainment comparison.</p>
              <p className="mt-3">If you are shown in our database or represent someone who is, or you own a photo we display, and you want it removed, email us at the address below and we will remove it promptly.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">9. Disclaimer of Warranties</h2>
              <p>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. We do not warrant that results will be accurate, that the Service will be uninterrupted, or that it will be error-free. The model can perform differently depending on the photo, lighting, and the person, so results may be less accurate for some faces than for others. The percentage shown with each match is a rescaled similarity score used for ranking. It is not a probability, and not proof of resemblance or identity. Results are for entertainment only.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">10. Limitation of Liability</h2>
              <p>To the fullest extent permitted by law, Ollie and its creators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to loss of data or reputation.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">11. No Affiliation or Endorsement</h2>
              <p>Ollie is not affiliated with, endorsed by, or connected to any celebrity shown, their representatives, or the organisations they work with. Being matched with a celebrity does not mean they endorse you or Ollie. Wikimedia Commons and Wikidata are projects of the Wikimedia Foundation, which is not affiliated with Ollie.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">12. Changes to Terms</h2>
              <p>We may change these terms at any time. Changes will be posted on this page with an updated date. Continued use after changes means you accept them.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">13. Governing Law</h2>
              <p>These terms are governed by the laws of the Province of British Columbia and the federal laws of Canada that apply there. Any dispute about them will be handled by the courts of British Columbia, unless the law where you live gives you the right to bring a claim elsewhere.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">14. Contact</h2>
              <p>Questions about these terms, or a takedown request? Contact us at <a href={`mailto:${EMAIL}`} className={link}>{EMAIL}</a>.</p>
            </section>

          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
