// Generated from Wikimedia Commons picks: freely licensed (public domain, CC0, CC BY, CC BY-SA), none flagged
// with personality rights. Files live in public/blog/img. Keep the credit + licence link wherever an image is shown.
export type BlogImage = {
  src: string
  thumb: string
  width: number
  height: number
  alt: string
  credit: string
  license: string
  licenseUrl: string
  sourceUrl: string
}

export const blogImages: Record<string, BlogImage> = {
  "how-face-recognition-works": {
    "src": "/blog/img/how-face-recognition-works.webp",
    "thumb": "/blog/img/how-face-recognition-works-sm.webp",
    "width": 1081,
    "height": 900,
    "alt": "Illustration of a face scanned with a mesh of facial recognition points",
    "credit": "teguhjatipras",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Face_Recognition_3252983.png"
  },
  "why-same-person-different-ai-results": {
    "src": "/blog/img/why-same-person-different-ai-results.webp",
    "thumb": "/blog/img/why-same-person-different-ai-results-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "Camera lens aperture blades seen close up",
    "credit": "D-Kuru",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Canon_EF-M_32mm_F1.4_STM_lens-aperture_blades_PNr%C2%B00803.jpg"
  },
  "face-recognition-math": {
    "src": "/blog/img/math-behind-your-face.webp",
    "thumb": "/blog/img/math-behind-your-face-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Labelled 3D model of the bones of the human skull",
    "credit": "https://www.scientificanimations.com",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:3D_Medical_Animation_Axial_Skeleton.jpg"
  },
  "how-cnns-see-faces": {
    "src": "/blog/img/how-cnns-see-faces.webp",
    "thumb": "/blog/img/how-cnns-see-faces-sm.webp",
    "width": 1280,
    "height": 529,
    "alt": "Diagram of a convolutional neural network: convolution, pooling, flatten and classification layers",
    "credit": "Irisbox",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Convolutional_Neural_Network.png"
  },
  "what-is-facial-embedding": {
    "src": "/blog/img/what-is-facial-embedding.webp",
    "thumb": "/blog/img/what-is-facial-embedding-sm.webp",
    "width": 1280,
    "height": 828,
    "alt": "Network graph of points clustered by similarity",
    "credit": "Martin Grandjean",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SocialNetworkAnalysis.png"
  },
  "why-ai-beats-human-eye": {
    "src": "/blog/img/why-ai-beats-human-eye.webp",
    "thumb": "/blog/img/why-ai-beats-human-eye-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Macro photo of a human iris",
    "credit": "Osmo Lundell",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Iris_of_human_male.jpg"
  },
  "face-detection-vs-recognition": {
    "src": "/blog/img/face-detection-vs-recognition.webp",
    "thumb": "/blog/img/face-detection-vs-recognition-sm.webp",
    "width": 1125,
    "height": 900,
    "alt": "Illustration of a phone projecting a 3D face mesh",
    "credit": "mikemacmarketing",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Facial_Recognition22.jpg"
  },
  "how-lighting-affects-recognition": {
    "src": "/blog/img/how-lighting-affects-recognition.webp",
    "thumb": "/blog/img/how-lighting-affects-recognition-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Two softbox lights in a photo studio",
    "credit": "Katie Chan",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PhotoSEL_LS21E52_Softbox_Studio_Lighting_Kit_(2).jpg"
  },
  "siamese-neural-networks-explained": {
    "src": "/blog/img/siamese-neural-networks-explained.webp",
    "thumb": "/blog/img/siamese-neural-networks-explained-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Illustration of a brain drawn as circuit traces",
    "credit": "mikemacmarketing / original posted on flickr Liam Huang / clipped and posted on…",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Artificial_Neural_Network_with_Chip.png"
  },
  "siamese-network-applications": {
    "src": "/blog/img/siamese-versatility.webp",
    "thumb": "/blog/img/siamese-versatility-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "MRI scan of a human brain",
    "credit": "511KeV",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MRI_Brain_T2_Cor_(14).jpg"
  },
  "contrastive-loss-explained": {
    "src": "/blog/img/contrastive-loss-explained.webp",
    "thumb": "/blog/img/contrastive-loss-explained-sm.webp",
    "width": 1125,
    "height": 900,
    "alt": "Chart of error falling over training steps for different learning rates",
    "credit": "Kirlf",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Steepest_descent.png"
  },
  "what-is-similarity-score": {
    "src": "/blog/img/what-is-similarity-score.webp",
    "thumb": "/blog/img/what-is-similarity-score-sm.webp",
    "width": 1003,
    "height": 900,
    "alt": "Heatmap of pairwise similarity scores",
    "credit": "Chamaemelum",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ezfst.png"
  },
  "find-your-celebrity-lookalike": {
    "src": "/blog/img/find-your-celebrity-lookalike.webp",
    "thumb": "/blog/img/find-your-celebrity-lookalike-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "A star on the Hollywood Walk of Fame",
    "credit": "Dietmar Rabich",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Los_Angeles_(California,_USA),_Hollywood_Boulevard,_The_Doors_--_2012_--_5040.jpg"
  },
  "why-everyone-has-doppelganger": {
    "src": "/blog/img/why-everyone-has-doppelganger.webp",
    "thumb": "/blog/img/why-everyone-has-doppelganger-sm.webp",
    "width": 694,
    "height": 900,
    "alt": "How They Met Themselves, Dante Gabriel Rossetti's drawing of a couple meeting their doubles",
    "credit": "Dante Gabriel Rossetti",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dante_Gabriel_Rossetti_-_How_They_Met_Themselves_(1851-60).jpg"
  },
  "most-matched-celebrities": {
    "src": "/blog/img/most-matched-celebrities.webp",
    "thumb": "/blog/img/most-matched-celebrities-sm.webp",
    "width": 1280,
    "height": 848,
    "alt": "The red carpet outside the Academy Awards",
    "credit": "Alan Light",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_carpet_(2086731832)_(2).jpg"
  },
  "why-some-celebrities-matched-more": {
    "src": "/blog/img/why-some-celebrities-matched-more.webp",
    "thumb": "/blog/img/why-some-celebrities-matched-more-sm.webp",
    "width": 995,
    "height": 823,
    "alt": "Black-and-white photo of press photographers crowding a stage",
    "credit": "Brent J. Irving",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Film_cameras_and_press_photographers_at_1960_DNC_(01).jpg"
  },
  "celebrity-match-different-era": {
    "src": "/blog/img/celebrity-match-different-era.webp",
    "thumb": "/blog/img/celebrity-match-different-era-sm.webp",
    "width": 1251,
    "height": 900,
    "alt": "Vintage box camera with a flash reflector",
    "credit": "Joe Haupt from USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vintage_Imperial_Reflex_620_Duo_Lens_Film_Camera,_A_Simple_Plastic_Box_Camera_(16403678691).jpg"
  },
  "selfie-vs-passport-match": {
    "src": "/blog/img/selfie-vs-passport-match.webp",
    "thumb": "/blog/img/selfie-vs-passport-match-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Passports from several countries",
    "credit": "Horizon206",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Four_Different_Passports.jpg"
  },
  "celebrities-that-fool-ai": {
    "src": "/blog/img/celebrities-that-fool-ai.webp",
    "thumb": "/blog/img/celebrities-that-fool-ai-sm.webp",
    "width": 1183,
    "height": 900,
    "alt": "Checker shadow illusion: two squares of the same grey that look different",
    "credit": "Original: Edward H. Adelson, vectorized by Pbroks13.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Checker_shadow_illusion.svg"
  },
  "what-celebrity-match-reveals": {
    "src": "/blog/img/what-celebrity-match-reveals.webp",
    "thumb": "/blog/img/what-celebrity-match-reveals-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "A human skull on display",
    "credit": "Federigo Federighi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Human_skull_at_human_anatomy_museum_(Pisa_university).jpg"
  },
  "why-people-say-you-look-like-someone": {
    "src": "/blog/img/science-of-you-look-like.webp",
    "thumb": "/blog/img/science-of-you-look-like-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Marble and bronze portrait busts in a museum gallery",
    "credit": "No Swan So Fine",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Interior_of_the_National_Portrait_Gallery,_London,_September_2023_08.jpg"
  },
  "why-humans-bad-at-faces": {
    "src": "/blog/img/why-humans-bad-at-faces.webp",
    "thumb": "/blog/img/why-humans-bad-at-faces-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "A street crowd reflected in a kaleidoscope of mirrored panels",
    "credit": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Street_crowd_reflecting_in_the_polyhedral_mirrors_of_the_station_Tokyu_Plaza_Omotesando,_Harajuku,_Tokyo,_Japan.jpg"
  },
  "prosopagnosia": {
    "src": "/blog/img/prosopagnosia.webp",
    "thumb": "/blog/img/prosopagnosia-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "3D brain model with the fusiform gyrus highlighted in red",
    "credit": "RAZVAN V. MARINESCU",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fusiform_-_DK_ATLAS_05.png"
  },
  "pareidolia-faces-everywhere": {
    "src": "/blog/img/pareidolia-faces-everywhere.webp",
    "thumb": "/blog/img/pareidolia-faces-everywhere-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Plastic water canisters whose caps and handles look like faces",
    "credit": "TeWeBs",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Camara_de_Lobos_Pareidolia_2.JPG"
  },
  "own-race-effect": {
    "src": "/blog/img/own-race-effect.webp",
    "thumb": "/blog/img/own-race-effect-sm.webp",
    "width": 1280,
    "height": 675,
    "alt": "Aerial view of a large crowd filling a city street",
    "credit": "Eromane",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LoveFestFeb122018.jpg"
  },
  "your-own-face": {
    "src": "/blog/img/your-own-face.webp",
    "thumb": "/blog/img/your-own-face-sm.webp",
    "width": 600,
    "height": 900,
    "alt": "A person's reflection in a rain puddle on the pavement",
    "credit": "Tomascastelazo",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bicycle_reflections.jpg"
  },
  "baby-face-features": {
    "src": "/blog/img/baby-face-features.webp",
    "thumb": "/blog/img/baby-face-features-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "A puppy with big eyes holding a toy ball",
    "credit": "Funkiestfarter",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gustavo_chewing_squeaky_toy_(super_cute).jpg"
  },
  "resting-face": {
    "src": "/blog/img/resting-face.webp",
    "thumb": "/blog/img/resting-face-sm.webp",
    "width": 604,
    "height": 900,
    "alt": "Leonardo da Vinci's Mona Lisa",
    "credit": "Leonardo da Vinci",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg"
  },
  "brain-recognises-face": {
    "src": "/blog/img/brain-recognises-face.webp",
    "thumb": "/blog/img/brain-recognises-face-sm.webp",
    "width": 1123,
    "height": 900,
    "alt": "Illustration of the human brain",
    "credit": "Courtesy of NIAID Ryan Kissinger",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brain_Lateral_(NIH_BioArt_60).png"
  },
  "best-photo-celebrity-match": {
    "src": "/blog/img/best-photo-celebrity-match.webp",
    "thumb": "/blog/img/best-photo-celebrity-match-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Four smartphones laid out showing their rear cameras",
    "credit": "IPHONE MAX",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:IPhone_camera.jpeg"
  },
  "best-lighting-for-match": {
    "src": "/blog/img/best-lighting-for-match.webp",
    "thumb": "/blog/img/best-lighting-for-match-sm.webp",
    "width": 732,
    "height": 900,
    "alt": "Daylight coming through an open window",
    "credit": "Rhododendrites",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Window_in_a_cafe_in_San_Gimignano_(02182)2.jpg"
  },
  "glasses-hats-hair": {
    "src": "/blog/img/glasses-hats-hair.webp",
    "thumb": "/blog/img/glasses-hats-hair-sm.webp",
    "width": 1280,
    "height": 898,
    "alt": "Two pairs of eyeglasses",
    "credit": "Jacek Halicki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2023_Okulary_korekcyjne.jpg"
  },
  "front-vs-rear-camera": {
    "src": "/blog/img/front-vs-rear-camera.webp",
    "thumb": "/blog/img/front-vs-rear-camera-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "A smartphone camera module on its circuit board",
    "credit": "Raimond Spekking",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Huawei_Y6_(2019,_model_MRD-LX1)_-_board_1_-_rear-facing_camera_Sunny_M13N01B-47215.jpg"
  },
  "bias-in-face-recognition": {
    "src": "/blog/img/bias-in-face-recognition.webp",
    "thumb": "/blog/img/bias-in-face-recognition-sm.webp",
    "width": 1280,
    "height": 854,
    "alt": "Bronze statue of Lady Justice holding scales",
    "credit": "DP Singh Bhullar",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Close-up_of_Lady_Justice_statue_holding_scales,_symbolizing_justice_and_fairness.jpg"
  },
  "privacy-and-face-recognition": {
    "src": "/blog/img/privacy-and-face-recognition.webp",
    "thumb": "/blog/img/privacy-and-face-recognition-sm.webp",
    "width": 1280,
    "height": 890,
    "alt": "A security camera above a 'Security cameras in use' sign",
    "credit": "Myotus",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vandal_dome-style_security_camera_next_to_signage_on_exterior_of_Target_store.jpg"
  },
  "history-of-face-recognition": {
    "src": "/blog/img/history-of-face-recognition.webp",
    "thumb": "/blog/img/history-of-face-recognition-sm.webp",
    "width": 884,
    "height": 900,
    "alt": "Alphonse Bertillon's own 1891 identification card with front and profile photos",
    "credit": "Alphonse Bertillon (1853-1914)",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphonse_Bertillon_-_fiche_anthropom%C3%A9trique_(1894).jpg"
  },
  "training-data-matters": {
    "src": "/blog/img/training-data-matters.webp",
    "thumb": "/blog/img/training-data-matters-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Rows of full bookshelves in a library",
    "credit": "Geonuch",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bookshelves_in_Faculty_of_Arts_Library,_Chulalongkorn_University.jpg"
  },
  "confidence-vs-accuracy": {
    "src": "/blog/img/confidence-vs-accuracy.webp",
    "thumb": "/blog/img/confidence-vs-accuracy-sm.webp",
    "width": 857,
    "height": 900,
    "alt": "Darts clustered on a dartboard",
    "credit": "kallerna",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tikkataulu.JPG"
  },
  "identical-twins-different-profiles": {
    "src": "/blog/img/identical-twins-different-profiles.webp",
    "thumb": "/blog/img/identical-twins-different-profiles-sm.webp",
    "width": 1192,
    "height": 897,
    "alt": "3D illustration of a DNA double helix",
    "credit": "National Human Genome Research Institute",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DNA_Double_Helix_by_NHGRI.jpg"
  },
  "expression-affects-matching": {
    "src": "/blog/img/expression-affects-matching.webp",
    "thumb": "/blog/img/expression-affects-matching-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "19th-century engraving of a face in an exaggerated expression of fear, from Duchenne's studies",
    "credit": "Guillaume Duchenne",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Expression_of_the_Emotions_Figure_20.png"
  },
  "makeup-affects-matching": {
    "src": "/blog/img/makeup-affects-matching.webp",
    "thumb": "/blog/img/makeup-affects-matching-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Makeup brushes of different sizes on a table",
    "credit": "Kandance拍攝",
    "license": "CC BY-SA 2.0 tw",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/tw/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blush_-_A_selection_of_makeup_brushes.jpg"
  },
  "aging-face-recognition": {
    "src": "/blog/img/aging-face-recognition.webp",
    "thumb": "/blog/img/aging-face-recognition-sm.webp",
    "width": 444,
    "height": 900,
    "alt": "A wooden hourglass with sand running through",
    "credit": "S Sepp",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wooden_hourglass_3.jpg"
  },
  "photo-angle-celebrity-match": {
    "src": "/blog/img/photo-angle-celebrity-match.webp",
    "thumb": "/blog/img/photo-angle-celebrity-match-sm.webp",
    "width": 948,
    "height": 900,
    "alt": "A camera tripod head with adjustment handles",
    "credit": "Dmitry Makeev",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Manfrotto_tripod_heads_804RC2.jpg"
  },
  "group-photo-matching": {
    "src": "/blog/img/group-photo-matching.webp",
    "thumb": "/blog/img/group-photo-matching-sm.webp",
    "width": 1280,
    "height": 881,
    "alt": "Group photograph of the 1927 Solvay physics conference",
    "credit": "Benjamin Couprie",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Solvay_conference_1927_Version2.jpg"
  },
  "face-shape-guide": {
    "src": "/blog/img/face-shape-guide.webp",
    "thumb": "/blog/img/face-shape-guide-sm.webp",
    "width": 696,
    "height": 900,
    "alt": "Colourful geometric pattern built from triangles and hexagons",
    "credit": "Neirenz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Amper%27s_Geometric_Shape_Art_Project.jpg"
  },
  "celebrity-face-evolution": {
    "src": "/blog/img/celebrity-face-evolution.webp",
    "thumb": "/blog/img/celebrity-face-evolution-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Close-up of a reel of 35mm film",
    "credit": "Coyau",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:8_mm_Kodak_safety_film_reel_06.jpg"
  },
  "golden-ratio-face": {
    "src": "/blog/img/golden-ratio-face.webp",
    "thumb": "/blog/img/golden-ratio-face-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "A spiral staircase seen from above, curling like a golden spiral",
    "credit": "Brad Hammonds",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Golden_Spiral_by_Brad_Hammonds.jpg"
  },
  "face-attractiveness-research": {
    "src": "/blog/img/face-attractiveness-research.webp",
    "thumb": "/blog/img/face-attractiveness-research-sm.webp",
    "width": 657,
    "height": 900,
    "alt": "Leonardo da Vinci's Vitruvian Man drawing",
    "credit": "Leonardo da Vinci",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vitruvian.jpg"
  },
  "face-reading-pseudoscience": {
    "src": "/blog/img/face-reading-pseudoscience.webp",
    "thumb": "/blog/img/face-reading-pseudoscience-sm.webp",
    "width": 1128,
    "height": 900,
    "alt": "Ceramic phrenology heads mapped with supposed character regions",
    "credit": "Waters.Justin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phrenology_Head_Bust.jpg"
  },
  "face-memory-psychology": {
    "src": "/blog/img/face-memory-psychology.webp",
    "thumb": "/blog/img/face-memory-psychology-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "3D brain model with the hippocampus highlighted in red",
    "credit": "RAZVAN V. MARINESCU",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hippocampus_-_DK_ATLAS.png"
  },
  "weight-change-and-matching": {
    "src": "/blog/img/weight-change-and-matching.webp",
    "thumb": "/blog/img/weight-change-and-matching-sm.webp",
    "width": 1209,
    "height": 900,
    "alt": "An ornate antique brass balance scale",
    "credit": "Nikodem Nijaki",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Balance_scale_IMGP9722.jpg"
  },
  "hair-color-affects-matching": {
    "src": "/blog/img/hair-color-affects-matching.webp",
    "thumb": "/blog/img/hair-color-affects-matching-sm.webp",
    "width": 676,
    "height": 900,
    "alt": "Blonde hair being coloured with purple dye",
    "credit": "WhatamIdoing",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dyeing_hair_purple.png"
  },
  "beard-affects-matching": {
    "src": "/blog/img/beard-affects-matching.webp",
    "thumb": "/blog/img/beard-affects-matching-sm.webp",
    "width": 656,
    "height": 900,
    "alt": "A safety razor and shaving brush on a stand",
    "credit": "Evan-Amos",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shaving-Set.jpg"
  },
  "ollie-how-it-works": {
    "src": "/blog/img/ollie-how-it-works.webp",
    "thumb": "/blog/img/ollie-how-it-works-sm.webp",
    "width": 1248,
    "height": 630,
    "alt": "A graphics card, the kind of chip used to run neural networks",
    "credit": "Asim18 at English Wikipedia",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gpu-connections.png"
  },
  "improving-ollie-results": {
    "src": "/blog/img/improving-ollie-results.webp",
    "thumb": "/blog/img/improving-ollie-results-sm.webp",
    "width": 604,
    "height": 900,
    "alt": "A softbox light set up in a small photo studio",
    "credit": "THOR",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Still_life_photography_studio_setup_with_softboxes,_by_geishaboy500.jpg"
  },
  "understanding-your-results": {
    "src": "/blog/img/understanding-your-results.webp",
    "thumb": "/blog/img/understanding-your-results-sm.webp",
    "width": 1280,
    "height": 512,
    "alt": "Colourful bar chart",
    "credit": "allixpeeke",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:United_States_presidential_election_ordinal_results_bar_graph_(Expanded).png"
  },
  "vggface2-explained": {
    "src": "/blog/img/vggface2-explained.webp",
    "thumb": "/blog/img/vggface2-explained-sm.webp",
    "width": 1280,
    "height": 786,
    "alt": "Archive binders full of photo slides and negatives",
    "credit": "Silvia Florindi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Archivio_Fotografico_IIPP.jpg"
  },
  "resnet-face-recognition": {
    "src": "/blog/img/resnet-face-recognition.webp",
    "thumb": "/blog/img/resnet-face-recognition-sm.webp",
    "width": 1280,
    "height": 693,
    "alt": "Diagram of a residual block: two layers plus an identity shortcut, x + F(x)",
    "credit": "LunarLullaby",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ResBlock.png"
  },
  "arcface-explained": {
    "src": "/blog/img/arcface-explained.webp",
    "thumb": "/blog/img/arcface-explained-sm.webp",
    "width": 1152,
    "height": 900,
    "alt": "3D plot of a unit sphere with an arc drawn across its surface",
    "credit": "BagLuke",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sphere_with_an_opaque_set_of_type_(1,_2)_(figure_B).png"
  },
  "face-recognition-benchmark": {
    "src": "/blog/img/face-recognition-benchmark.webp",
    "thumb": "/blog/img/face-recognition-benchmark-sm.webp",
    "width": 729,
    "height": 900,
    "alt": "A mechanical stopwatch",
    "credit": "Stefan (Diskussion). Original uploader was StefanPohl at German Wikipedia",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stoppuhr_hanhart.jpg"
  },
  "symmetrical-faces": {
    "src": "/blog/img/symmetrical-faces.webp",
    "thumb": "/blog/img/symmetrical-faces-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "A perfectly mirror-symmetric butterfly graphic",
    "credit": "Silharstak",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PHOBIA_Symbol.png"
  },
  "uncanny-valley": {
    "src": "/blog/img/uncanny-valley.webp",
    "thumb": "/blog/img/uncanny-valley-sm.webp",
    "width": 600,
    "height": 900,
    "alt": "Close-up of a humanoid robot with a human-like face",
    "credit": "Sven Volkens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Humanoider-Roboter-DASA.JPG"
  },
  "accuracy-across-demographics": {
    "src": "/blog/img/accuracy-across-demographics.webp",
    "thumb": "/blog/img/accuracy-across-demographics-sm.webp",
    "width": 1280,
    "height": 851,
    "alt": "A world globe turned to show Africa and Asia",
    "credit": "Wendy Cope",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Globe_with_yellow_background_1.jpg"
  },
  "celebrity-doppelgangers-throughout-history": {
    "src": "/blog/img/celebrity-doppelgangers-throughout-history.webp",
    "thumb": "/blog/img/celebrity-doppelgangers-throughout-history-sm.webp",
    "width": 684,
    "height": 900,
    "alt": "19th-century illustration of the identical Dromio twins from Shakespeare's Comedy of Errors",
    "credit": "J. Coghlan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Comedy_of_errors_IV.i.jpg"
  },
  "celebrity-resemblance-and-self-image": {
    "src": "/blog/img/celebrity-resemblance-and-self-image.webp",
    "thumb": "/blog/img/celebrity-resemblance-and-self-image-sm.webp",
    "width": 367,
    "height": 900,
    "alt": "An antique framed mirror hanging on a wall",
    "credit": "Napier Andrews",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Antique_Trumeau_reproduction.jpg"
  },
  "celebrity-database-how-built": {
    "src": "/blog/img/celebrity-database-how-built.webp",
    "thumb": "/blog/img/celebrity-database-how-built-sm.webp",
    "width": 1064,
    "height": 900,
    "alt": "An open drawer in a wooden library card catalogue",
    "credit": "Dr. Marcus Gossler",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schlagwortkatalog.jpg"
  },
  "what-makes-a-face-memorable": {
    "src": "/blog/img/what-makes-a-face-memorable.webp",
    "thumb": "/blog/img/what-makes-a-face-memorable-sm.webp",
    "width": 939,
    "height": 900,
    "alt": "A 16th-century Holbein portrait miniature of a man in a black cap",
    "credit": "Lucas Horenbout",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Portrait_miniature_of_a_gentleman,_possibly_Charles_Brandon,_Duke_of_Suffolk.jpg"
  },
  "celebrities-who-look-alike": {
    "src": "/blog/img/celebrities-who-look-alike.webp",
    "thumb": "/blog/img/celebrities-who-look-alike-sm.webp",
    "width": 1280,
    "height": 852,
    "alt": "Ancient Roman coin showing the two matching faces of the god Janus",
    "credit": "Somerset County Council, Ciorstaidh Hayward Trevarthen",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Roman_coin,_Republican_denarius_of_M_Furius_Philus_(FindID_393742).jpg"
  },
  "what-is-my-face-shape": {
    "src": "/blog/img/what-is-my-face-shape.webp",
    "thumb": "/blog/img/what-is-my-face-shape-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Coiled tailor's measuring tape on a cloth",
    "credit": "Tool Dude8mm",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tape_Measure_Tailor_Tape_Measure_387277_Edited_2020_(49917401241).jpg"
  },
  "heart-shaped-face": {
    "src": "/blog/img/heart-shaped-face.webp",
    "thumb": "/blog/img/heart-shaped-face-sm.webp",
    "width": 919,
    "height": 1280,
    "alt": "Botticelli's portrait of a young woman in profile with braided hair",
    "credit": "Sandro Botticelli",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Profilbildnis_einer_jungen_Frau_-_Gem%C3%A4ldegalerie_Berlin_-_5252728.jpg"
  },
  "oblong-face-shape": {
    "src": "/blog/img/oblong-face-shape.webp",
    "thumb": "/blog/img/oblong-face-shape-sm.webp",
    "width": 932,
    "height": 1200,
    "alt": "El Greco's portrait of a nobleman with his hand on his chest, showing a long, narrow face",
    "credit": "El Greco",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:El_Greco_-_Nobleman_with_his_Hand_on_his_Chest_-_WGA10463.jpg"
  },
  "haircuts-for-round-faces": {
    "src": "/blog/img/haircuts-for-round-faces.webp",
    "thumb": "/blog/img/haircuts-for-round-faces-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "Hairdresser's holster filled with scissors and combs",
    "credit": "Lisa Risager from Denmark",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leather_belt_bag_with_various_tools_of_a_hairdresser_for_quick_access.jpg"
  },
  "round-face-haircuts-men": {
    "src": "/blog/img/round-face-haircuts-men.webp",
    "thumb": "/blog/img/round-face-haircuts-men-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Vintage barber tools laid out on a table: hand clippers, razor and scissors",
    "credit": "Thomas Quine",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Antique_barber%27s_tools_(42952164200).jpg"
  },
  "short-hair-round-face": {
    "src": "/blog/img/short-hair-round-face.webp",
    "thumb": "/blog/img/short-hair-round-face-sm.webp",
    "width": 1176,
    "height": 1280,
    "alt": "Roman marble bust of a woman with a round face and a high curled hairstyle",
    "credit": "Bibi Saint-Pol",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bust_Roman_woman_Glyptothek_Munich_333.jpg"
  },
  "haircuts-for-oval-faces": {
    "src": "/blog/img/haircuts-for-oval-faces.webp",
    "thumb": "/blog/img/haircuts-for-oval-faces-sm.webp",
    "width": 874,
    "height": 1280,
    "alt": "The bust of Nefertiti, an often-cited example of an oval face",
    "credit": "Philip Pikart",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nofretete_Neues_Museum.jpg"
  },
  "oval-face-haircuts-men": {
    "src": "/blog/img/oval-face-haircuts-men.webp",
    "thumb": "/blog/img/oval-face-haircuts-men-sm.webp",
    "width": 852,
    "height": 1280,
    "alt": "Marble bust of Antinous with short wavy hair",
    "credit": "Jebulon",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Antinous_detail_bust_NAMAthens.jpg"
  },
  "square-face-hairstyles": {
    "src": "/blog/img/square-face-hairstyles.webp",
    "thumb": "/blog/img/square-face-hairstyles-sm.webp",
    "width": 853,
    "height": 1280,
    "alt": "Marble portrait head of the Roman emperor Vespasian with a broad, square jaw",
    "credit": "José Luiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bust_of_Vespasian_(loan_from_Ny_Carlsberg_Glyptotek)_-_Glyptothek_-_Munich_-_Germany_2017.jpg"
  },
  "diamond-face-shape-hairstyles": {
    "src": "/blog/img/diamond-face-shape-hairstyles.webp",
    "thumb": "/blog/img/diamond-face-shape-hairstyles-sm.webp",
    "width": 895,
    "height": 1280,
    "alt": "Modigliani portrait of a young woman with an elongated face and hair pinned up",
    "credit": "Amedeo Modigliani",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Portrait_of_a_Young_Woman,_Amedeo_Modigliani,_1918,_New_Orleans_Museum_of_Art.jpg"
  },
  "triangle-face-shape": {
    "src": "/blog/img/triangle-face-shape.webp",
    "thumb": "/blog/img/triangle-face-shape-sm.webp",
    "width": 800,
    "height": 1280,
    "alt": "Fayum mummy portrait of a bearded man from Roman Egypt",
    "credit": "Jebulon",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fayum_egyptian_funerary_portrait_1627_NAMAthens.jpg"
  },
  "hairstyles-for-long-faces": {
    "src": "/blog/img/hairstyles-for-long-faces.webp",
    "thumb": "/blog/img/hairstyles-for-long-faces-sm.webp",
    "width": 1105,
    "height": 1280,
    "alt": "Rossetti's Lady Lilith combing her long hair",
    "credit": "Dante Gabriel Rossetti",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dante_Gabriel_Rossetti_-_Lady_Lilith.jpg"
  },
  "heart-shaped-face-haircuts": {
    "src": "/blog/img/heart-shaped-face-haircuts.webp",
    "thumb": "/blog/img/heart-shaped-face-haircuts-sm.webp",
    "width": 1280,
    "height": 1128,
    "alt": "19th-century lithograph of a hairdresser styling a client's hair",
    "credit": "Auguste Bouquet",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pauvre_libert%C3%A9,_qu%27elle_queue!!_(BM_1989,0128.26).jpg"
  },
  "face-shapes-men": {
    "src": "/blog/img/face-shapes-men.webp",
    "thumb": "/blog/img/face-shapes-men-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "Classical marble bust of a bearded man with short curly hair",
    "credit": "Yair Haklai",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Roman_bust.jpg"
  },
  "oval-vs-round-face": {
    "src": "/blog/img/oval-vs-round-face.webp",
    "thumb": "/blog/img/oval-vs-round-face-sm.webp",
    "width": 1081,
    "height": 1280,
    "alt": "Vermeer's Girl with a Pearl Earring",
    "credit": "Johannes Vermeer",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:1665_Girl_with_a_Pearl_Earring.jpg"
  },
  "best-haircut-for-face-shape": {
    "src": "/blog/img/best-haircut-for-face-shape.webp",
    "thumb": "/blog/img/best-haircut-for-face-shape-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Row of vintage barber chairs in an old barbershop",
    "credit": "PattayaPatrol",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DSCF1083_Vintage_red_barber_chairs_in_a_rustic_wooden_shop_waiting_for_the_next_customer.jpg"
  },
  "haircuts-for-chubby-faces": {
    "src": "/blog/img/haircuts-for-chubby-faces.webp",
    "thumb": "/blog/img/haircuts-for-chubby-faces-sm.webp",
    "width": 872,
    "height": 1280,
    "alt": "Rembrandt's portrait of a nobleman in a fur hat with a moustache",
    "credit": "Rembrandt",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rembrandt_van_Rijn_-_A_Polish_nobleman.jpg"
  },
  "hairstyles-for-big-forehead": {
    "src": "/blog/img/hairstyles-for-big-forehead.webp",
    "thumb": "/blog/img/hairstyles-for-big-forehead-sm.webp",
    "width": 846,
    "height": 1280,
    "alt": "Leonardo da Vinci's Mona Lisa",
    "credit": "Leonardo da Vinci",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mona_Lisa.jpg"
  },
  "curly-hair-round-face": {
    "src": "/blog/img/curly-hair-round-face.webp",
    "thumb": "/blog/img/curly-hair-round-face-sm.webp",
    "width": 800,
    "height": 1280,
    "alt": "Roman marble portrait of a woman with a high crown of curls",
    "credit": "Osama Shukir Muhammed Amin FRCP(Glasg)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marble_head_of_an_unidentified_Roman_woman_with_a_curly_toupee,_80-100_CE._Assigned_as_3rd_party_ownership_in_1947_CE._Altes_Museum,_Berlin,_Germany.jpg"
  },
  "layered-haircut-round-face": {
    "src": "/blog/img/layered-haircut-round-face.webp",
    "thumb": "/blog/img/layered-haircut-round-face-sm.webp",
    "width": 1280,
    "height": 1075,
    "alt": "Wooden hair combs displayed in a shop",
    "credit": "Valenzuela400",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hu%C4%81_M%C3%B9l%C3%A1n_Red_sandalwood_hair_%E6%A0%89_combs_Pterocarpus_santalinus20.jpg"
  },
  "bangs-for-round-face": {
    "src": "/blog/img/bangs-for-round-face.webp",
    "thumb": "/blog/img/bangs-for-round-face-sm.webp",
    "width": 1280,
    "height": 960,
    "alt": "Hair accessories laid out: combs, brush, clips, pins and hair ties",
    "credit": "Stilfehler",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hair_Braiding_Equipment.JPG"
  },
  "celebrity-face-shapes": {
    "src": "/blog/img/celebrity-face-shapes.webp",
    "thumb": "/blog/img/celebrity-face-shapes-sm.webp",
    "width": 1074,
    "height": 1280,
    "alt": "Leonardo da Vinci's study of the proportions of the human face",
    "credit": "Leonardo da Vinci (photo: Luc Viatour)",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%C3%89tude_visage_Luc_Viatour.jpg"
  },
  "celebrities-with-round-faces": {
    "src": "/blog/img/celebrities-with-round-faces.webp",
    "thumb": "/blog/img/celebrities-with-round-faces-sm.webp",
    "width": 1280,
    "height": 819,
    "alt": "Star on the Hollywood Walk of Fame",
    "credit": "Dietmar Rabich",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Los_Angeles_(California,_USA),_Hollywood_Boulevard,_Gregory_Peck_--_2012_--_4975.jpg"
  },
  "celebrities-with-oval-faces": {
    "src": "/blog/img/celebrities-with-oval-faces.webp",
    "thumb": "/blog/img/celebrities-with-oval-faces-sm.webp",
    "width": 982,
    "height": 1280,
    "alt": "Vintage folding film camera",
    "credit": "Joe Haupt from USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vintage_Kodak_Junior_Six-20_Series_II_Folding_Film_Camera_(15869618824).jpg"
  },
  "celebrities-with-heart-shaped-faces": {
    "src": "/blog/img/celebrities-with-heart-shaped-faces.webp",
    "thumb": "/blog/img/celebrities-with-heart-shaped-faces-sm.webp",
    "width": 1280,
    "height": 998,
    "alt": "19th-century photograph of the ancient theatre at Pompeii",
    "credit": "Giacomo Brogi",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pompeii-_Tragic_or_Covered_Theatre,_No._5035_(SM_stf1550).png"
  },
  "celebrities-with-square-faces": {
    "src": "/blog/img/celebrities-with-square-faces.webp",
    "thumb": "/blog/img/celebrities-with-square-faces-sm.webp",
    "width": 1280,
    "height": 724,
    "alt": "Vintage film clapperboard",
    "credit": "Bernd Schwabe in Hannover",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:1992-04-24_Filmklappe_Filmschindel_Gedanken_3.jpg"
  },
  "celebrity-haircuts-by-face-shape": {
    "src": "/blog/img/celebrity-haircuts-by-face-shape.webp",
    "thumb": "/blog/img/celebrity-haircuts-by-face-shape-sm.webp",
    "width": 706,
    "height": 1280,
    "alt": "Antique leather barber chair",
    "credit": "Eric Polk",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Antique_%27Star%27_model_barber_chair.jpg"
  },
  "haircuts-for-thin-hair": {
    "src": "/blog/img/haircuts-for-thin-hair.webp",
    "thumb": "/blog/img/haircuts-for-thin-hair-sm.webp",
    "width": 1280,
    "height": 914,
    "alt": "Wooden bristle hairbrush",
    "credit": "Musical Linguist",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hairbrush_flat.JPG"
  },
  "hairstyles-for-women-over-50": {
    "src": "/blog/img/hairstyles-for-women-over-50.webp",
    "thumb": "/blog/img/hairstyles-for-women-over-50-sm.webp",
    "width": 949,
    "height": 1280,
    "alt": "Rembrandt portrait of a woman in a white ruff collar",
    "credit": "Rembrandt",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rembrandt_-_Portrait_of_a_woman_-_MET_DP145913.jpg"
  },
  "haircuts-for-men-over-50": {
    "src": "/blog/img/haircuts-for-men-over-50.webp",
    "thumb": "/blog/img/haircuts-for-men-over-50-sm.webp",
    "width": 988,
    "height": 1280,
    "alt": "Rembrandt's self-portrait from 1659, aged about 53",
    "credit": "Rembrandt",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg"
  },
  "receding-hairline-haircuts": {
    "src": "/blog/img/receding-hairline-haircuts.webp",
    "thumb": "/blog/img/receding-hairline-haircuts-sm.webp",
    "width": 943,
    "height": 1280,
    "alt": "Marble portrait of Julius Caesar showing a receding hairline",
    "credit": "Ángel M. Felicísimo from Mérida, España",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Retrato_de_Julio_C%C3%A9sar_(26724093101)_(cropped).jpg"
  },
  "balding-haircuts-men": {
    "src": "/blog/img/balding-haircuts-men.webp",
    "thumb": "/blog/img/balding-haircuts-men-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "Marble bust of Socrates with a balding head and full beard",
    "credit": "Eric Gaba (Sting)",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Socrate_du_Louvre.jpg"
  },
  "haircuts-for-thick-hair-men": {
    "src": "/blog/img/haircuts-for-thick-hair-men.webp",
    "thumb": "/blog/img/haircuts-for-thick-hair-men-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Horn combs laid out on a table",
    "credit": "Orce Wiki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Combs_-_Macedonian_barber_craft.jpg"
  },
  "gray-hair-styles": {
    "src": "/blog/img/gray-hair-styles.webp",
    "thumb": "/blog/img/gray-hair-styles-sm.webp",
    "width": 1076,
    "height": 1280,
    "alt": "Old master portrait of a man with long grey hair",
    "credit": "Rembrandt",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rembrandt_Harmensz._van_Rijn_-_Portrait_of_a_white-haired_man_-_Google_Art_Project.jpg"
  },
  "hairstyles-that-make-you-look-younger": {
    "src": "/blog/img/hairstyles-that-make-you-look-younger.webp",
    "thumb": "/blog/img/hairstyles-that-make-you-look-younger-sm.webp",
    "width": 1280,
    "height": 1251,
    "alt": "Vintage chrome hair dryer on a red background",
    "credit": "Dinkun Chen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HITACHI_HAIR_DRYER_HD-1650.jpg"
  },
  "what-makes-you-look-older": {
    "src": "/blog/img/what-makes-you-look-older.webp",
    "thumb": "/blog/img/what-makes-you-look-older-sm.webp",
    "width": 1280,
    "height": 950,
    "alt": "Three antique hourglasses",
    "credit": "Wellcome Collection",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:3_Hourglasses_Wellcome_L0011331.jpg"
  },
  "how-to-look-older": {
    "src": "/blog/img/how-to-look-older.webp",
    "thumb": "/blog/img/how-to-look-older-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Pocket watch on a silk tie",
    "credit": "photo-nic.co.uk nic chiro",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Antique_pocket_watch_(Unsplash).jpg"
  },
  "jawline": {
    "src": "/blog/img/jawline.webp",
    "thumb": "/blog/img/jawline-sm.webp",
    "width": 1174,
    "height": 1280,
    "alt": "Detail of Caravaggio's David and Goliath showing David's face in profile",
    "credit": "Caravaggio",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:David_and_Goliath-Caravaggio_(c.1610)_(cropped_focus_on_David%27s_face).jpg"
  },
  "beard-styles-for-face-shape": {
    "src": "/blog/img/beard-styles-for-face-shape.webp",
    "thumb": "/blog/img/beard-styles-for-face-shape-sm.webp",
    "width": 1280,
    "height": 1035,
    "alt": "Safety razor, shaving brush and mug",
    "credit": "Hustvedt",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Safety_razor_shaving_kit.jpg"
  },
  "beard-styles-round-face": {
    "src": "/blog/img/beard-styles-round-face.webp",
    "thumb": "/blog/img/beard-styles-round-face-sm.webp",
    "width": 962,
    "height": 1280,
    "alt": "Marble bust of Marcus Aurelius with a full curly beard",
    "credit": "Daniel Martin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marcus_Aurelius_marble_bust_(3x4_cropped).jpg"
  },
  "patchy-beard": {
    "src": "/blog/img/patchy-beard.webp",
    "thumb": "/blog/img/patchy-beard-sm.webp",
    "width": 591,
    "height": 1280,
    "alt": "Black electric beard trimmer",
    "credit": "Bachelot Pierre J-P",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tondeuse_corporelle.jpg"
  },
  "mustache-styles": {
    "src": "/blog/img/mustache-styles.webp",
    "thumb": "/blog/img/mustache-styles-sm.webp",
    "width": 1280,
    "height": 1225,
    "alt": "Antique porcelain moustache cup with a guard to keep the moustache dry",
    "credit": "Richard Huber",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barttasse,_Tirschenreuth_um_1880.jpg"
  },
  "eyebrow-shapes": {
    "src": "/blog/img/eyebrow-shapes.webp",
    "thumb": "/blog/img/eyebrow-shapes-sm.webp",
    "width": 1280,
    "height": 498,
    "alt": "Three pairs of slanted tweezers",
    "credit": "Evan-Amos",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tweezers-variety.jpg"
  },
  "glasses-for-round-face": {
    "src": "/blog/img/glasses-for-round-face.webp",
    "thumb": "/blog/img/glasses-for-round-face-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Eyeglasses resting on a magazine beside a glass of red wine",
    "credit": "Aliis Sinisalu aliissinisalu",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Enjoying_a_book_with_a_glass_of_wine_(Unsplash).jpg"
  },
  "glasses-for-oval-face": {
    "src": "/blog/img/glasses-for-oval-face.webp",
    "thumb": "/blog/img/glasses-for-oval-face-sm.webp",
    "width": 990,
    "height": 890,
    "alt": "Chart of eyeglass lens shapes from an 1892 optician's book",
    "credit": "Phillips, R. J. (Richard Jones)",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spectacles_and_eyeglasses-_their_forms,_mounting_and_proper_adjustment_1923_(5th_edition)_Fig._10.jpg"
  },
  "glasses-for-square-face": {
    "src": "/blog/img/glasses-for-square-face.webp",
    "thumb": "/blog/img/glasses-for-square-face-sm.webp",
    "width": 1280,
    "height": 850,
    "alt": "Round wire-frame spectacles",
    "credit": "Wellcome Collection",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_pair_of_Spectacles_Wellcome_L0044001.jpg"
  },
  "sunglasses-for-face-shape": {
    "src": "/blog/img/sunglasses-for-face-shape.webp",
    "thumb": "/blog/img/sunglasses-for-face-shape-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Sunglasses resting on a rock outdoors",
    "credit": "Ildar Sagdejev (Specious)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2008-07-27_Sunglasses.jpg"
  },
  "types-of-haircuts-men": {
    "src": "/blog/img/types-of-haircuts-men.webp",
    "thumb": "/blog/img/types-of-haircuts-men-sm.webp",
    "width": 587,
    "height": 1280,
    "alt": "Spinning barber pole outside a barbershop",
    "credit": "Daderot",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barber_pole_-_San_Francisco,_CA.jpg"
  },
  "fade-vs-taper": {
    "src": "/blog/img/fade-vs-taper.webp",
    "thumb": "/blog/img/fade-vs-taper-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Antique manual hair clippers",
    "credit": "Orce Wiki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trimming_clippers_-_Macedonian_barber_craft.jpg"
  },
  "buzz-cut-face-shape": {
    "src": "/blog/img/buzz-cut-face-shape.webp",
    "thumb": "/blog/img/buzz-cut-face-shape-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "White electric hair clipper with a guard comb",
    "credit": "Batholith",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Electric_hair_clipper_(1).jpg"
  },
  "wolf-cut": {
    "src": "/blog/img/wolf-cut.webp",
    "thumb": "/blog/img/wolf-cut-sm.webp",
    "width": 1025,
    "height": 1280,
    "alt": "Grey wolf lying on rocks",
    "credit": "USFWS/Gary Kramer",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Grey_Wolf_Portrait.jpg"
  },
  "curtain-bangs": {
    "src": "/blog/img/curtain-bangs.webp",
    "thumb": "/blog/img/curtain-bangs-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Professional hairdressing scissors",
    "credit": "Pittigrilli",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Standard-type_haircutting_shears_for_hairdressers.jpg"
  },
  "middle-part-men": {
    "src": "/blog/img/middle-part-men.webp",
    "thumb": "/blog/img/middle-part-men-sm.webp",
    "width": 1000,
    "height": 667,
    "alt": "Set of pocket combs",
    "credit": "Math Wiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Metal_pocket_combs_and_leather_sheaths.jpg"
  },
  "how-to-ask-for-a-haircut": {
    "src": "/blog/img/how-to-ask-for-a-haircut.webp",
    "thumb": "/blog/img/how-to-ask-for-a-haircut-sm.webp",
    "width": 720,
    "height": 1280,
    "alt": "Front of a barbershop on a quiet street",
    "credit": "ArrayPirate",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DS_Barbershop_in_Brunswick_Roggenkamp_1_38112_Brunswick.jpg"
  },
  "body-types-women": {
    "src": "/blog/img/body-types-women.webp",
    "thumb": "/blog/img/body-types-women-sm.webp",
    "width": 969,
    "height": 1280,
    "alt": "The Venus de Milo statue",
    "credit": "Wilfredor",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Venus_de_Milo_from_Paris_Project,_44.jpg"
  },
  "body-types-men": {
    "src": "/blog/img/body-types-men.webp",
    "thumb": "/blog/img/body-types-men-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "Two men's jackets on dress forms in a tailor's window",
    "credit": "Peachyeung316",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Two_Jacket_on_the_Tailor_M_Shop.jpg"
  },
  "apple-body-shape": {
    "src": "/blog/img/apple-body-shape.webp",
    "thumb": "/blog/img/apple-body-shape-sm.webp",
    "width": 1280,
    "height": 1160,
    "alt": "A red apple",
    "credit": "Abhijit Tembhekar from Mumbai, India",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_Apple.jpg"
  },
  "inverted-triangle-body-shape": {
    "src": "/blog/img/inverted-triangle-body-shape.webp",
    "thumb": "/blog/img/inverted-triangle-body-shape-sm.webp",
    "width": 917,
    "height": 1280,
    "alt": "Engraving of the Farnese Hercules from behind, showing broad shoulders and a narrow waist",
    "credit": "Hendrik Goltzius",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hendrick_Goltzius_-_Farnese_Hercules_-_Google_Art_Project.jpg"
  },
  "how-to-dress-for-your-body-type": {
    "src": "/blog/img/how-to-dress-for-your-body-type.webp",
    "thumb": "/blog/img/how-to-dress-for-your-body-type-sm.webp",
    "width": 720,
    "height": 1280,
    "alt": "Mannequin dressed in a fitted outfit in a menswear shop",
    "credit": "Mostafameraji",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mannequin,_Shop_windows_in_Georgia-Tbilisi_%D9%88%DB%8C%D8%AA%D8%B1%DB%8C%D9%86_%D9%85%D8%BA%D8%A7%D8%B2%D9%87_%D9%87%D8%A7_%D8%AF%D8%B1_%D8%AA%D9%81%D9%84%DB%8C%D8%B3-_%D9%85%D8%A7%D9%86%DA%A9%D9%86_%D9%87%D8%A7_01.jpg"
  },
  "how-to-look-taller": {
    "src": "/blog/img/how-to-look-taller.webp",
    "thumb": "/blog/img/how-to-look-taller-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "Giraffe's head and neck against the sky",
    "credit": "Dietmar Rabich",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kruger_National_Park_(ZA),_Giraffe_--_2024_--_0431.jpg"
  },
  "outfits-for-tall-women": {
    "src": "/blog/img/outfits-for-tall-women.webp",
    "thumb": "/blog/img/outfits-for-tall-women-sm.webp",
    "width": 1280,
    "height": 960,
    "alt": "Interior of a colourful clothing boutique",
    "credit": "Steffen Mokosch",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ArtAmbient_boutique_interior_Arta.jpg"
  },
  "how-should-a-suit-fit": {
    "src": "/blog/img/how-should-a-suit-fit.webp",
    "thumb": "/blog/img/how-should-a-suit-fit-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "Close-up of a grey suit jacket lapel",
    "credit": "Cantabrucu",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spanish_tailoring_lapel.jpg"
  },
  "how-to-look-slimmer-in-clothes": {
    "src": "/blog/img/how-to-look-slimmer-in-clothes.webp",
    "thumb": "/blog/img/how-to-look-slimmer-in-clothes-sm.webp",
    "width": 1280,
    "height": 960,
    "alt": "Stacked bolts of pinstripe suiting fabric",
    "credit": "Grendelkhan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Suit_cloth_for_sale_at_Mood.jpg"
  },
  "color-analysis": {
    "src": "/blog/img/color-analysis.webp",
    "thumb": "/blog/img/color-analysis-sm.webp",
    "width": 1080,
    "height": 1080,
    "alt": "Johannes Itten's twelve-part colour wheel",
    "credit": "Johannes Itten",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%A6%D0%B2%D0%B5%D1%82%D0%BE%D0%B2%D0%BE%D0%B9_%D0%BA%D1%80%D1%83%D0%B3_ryb_12_%D1%86%D0%B2%D0%B5%D1%82%D0%BE%D0%B2.png"
  },
  "what-colors-look-good-on-me": {
    "src": "/blog/img/what-colors-look-good-on-me.webp",
    "thumb": "/blog/img/what-colors-look-good-on-me-sm.webp",
    "width": 1280,
    "height": 834,
    "alt": "Fabric swatches in red, purple, green, yellow and teal",
    "credit": "Textile and Fibre Technology, CSIRO",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_1853_Fabric_Swatches.jpg"
  },
  "old-money-style-men": {
    "src": "/blog/img/old-money-style-men.webp",
    "thumb": "/blog/img/old-money-style-men-sm.webp",
    "width": 1280,
    "height": 837,
    "alt": "Brown leather penny loafer",
    "credit": "Wikipedia-ce",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Penny_Loafer.jpg"
  },
  "smart-casual-men": {
    "src": "/blog/img/smart-casual-men.webp",
    "thumb": "/blog/img/smart-casual-men-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Row of jackets and blazers on hangers",
    "credit": "Igor Ovsyannykov igorovsyannykov",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blazer_Jackets_on_Rack_(Unsplash).jpg"
  },
  "business-casual-men": {
    "src": "/blog/img/business-casual-men.webp",
    "thumb": "/blog/img/business-casual-men-sm.webp",
    "width": 1200,
    "height": 801,
    "alt": "Rail of dress shirts in blue, white and pink",
    "credit": "Modern Fellows",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Button_down_dress_shirts_for_men.jpg"
  },
  "capsule-wardrobe-men": {
    "src": "/blog/img/capsule-wardrobe-men.webp",
    "thumb": "/blog/img/capsule-wardrobe-men-sm.webp",
    "width": 1280,
    "height": 960,
    "alt": "Wardrobe of shirts and jackets hanging in neutral colours",
    "credit": "Aavindraa",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Boy_closet.jpg"
  },
  "preppy-style": {
    "src": "/blog/img/preppy-style.webp",
    "thumb": "/blog/img/preppy-style-sm.webp",
    "width": 1000,
    "height": 710,
    "alt": "Pair of leather boat shoes",
    "credit": "Antontushnov",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sperry.jpg"
  },
  "aesthetic-types": {
    "src": "/blog/img/aesthetic-types.webp",
    "thumb": "/blog/img/aesthetic-types-sm.webp",
    "width": 1280,
    "height": 854,
    "alt": "Vintage clothing shop with rails of denim and jackets",
    "credit": "Lordship100",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PICKNWEIGHT_-_VINTAGE_KILO_STORE.jpg"
  },
  "what-to-wear-on-a-first-date": {
    "src": "/blog/img/what-to-wear-on-a-first-date.webp",
    "thumb": "/blog/img/what-to-wear-on-a-first-date-sm.webp",
    "width": 1280,
    "height": 852,
    "alt": "Restaurant table for two with a candle and wine glasses",
    "credit": "PattayaPatrol",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DZ6_2629_A_cozy_table_for_two_-_soft_lights_a_single_orchid_and_the_promise_of_a_perfect_evening.jpg"
  },
  "glow-up-tips": {
    "src": "/blog/img/glow-up-tips.webp",
    "thumb": "/blog/img/glow-up-tips-sm.webp",
    "width": 1280,
    "height": 857,
    "alt": "Open compact mirror with a powder highlighter",
    "credit": "Vikiçizer",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Makyaj_03.JPG"
  },
  "how-to-look-good-in-photos": {
    "src": "/blog/img/how-to-look-good-in-photos.webp",
    "thumb": "/blog/img/how-to-look-good-in-photos-sm.webp",
    "width": 960,
    "height": 1280,
    "alt": "Smartphone camera lens close up",
    "credit": "人工知能",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mi_11_Pro_camera_lens_group.jpg"
  }
}
