// Generated from Wikimedia Commons picks: freely licensed (public domain, CC0, CC BY, CC BY-SA), none flagged
// with personality rights. Files live in public/blog/img. Keep the credit + licence link wherever an image is shown.
export type BlogImage = {
  src: string
  thumb: string
  width: number
  height: number
  alt: string
  credit: string
  license: string
  licenseUrl: string
  sourceUrl: string
}

export const blogImages: Record<string, BlogImage> = {
  "how-face-recognition-works": {
    "src": "/blog/img/how-face-recognition-works.webp",
    "thumb": "/blog/img/how-face-recognition-works-sm.webp",
    "width": 1081,
    "height": 900,
    "alt": "Illustration of a face scanned with a mesh of facial recognition points",
    "credit": "teguhjatipras",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Face_Recognition_3252983.png"
  },
  "what-is-a-facial-fingerprint": {
    "src": "/blog/img/what-is-a-facial-fingerprint.webp",
    "thumb": "/blog/img/what-is-a-facial-fingerprint-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Close-up of the ridges of a human fingertip",
    "credit": "Zephyris",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fingerprint.jpg"
  },
  "why-same-person-different-ai-results": {
    "src": "/blog/img/why-same-person-different-ai-results.webp",
    "thumb": "/blog/img/why-same-person-different-ai-results-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "Camera lens aperture blades seen close up",
    "credit": "D-Kuru",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Canon_EF-M_32mm_F1.4_STM_lens-aperture_blades_PNr%C2%B00803.jpg"
  },
  "math-behind-your-face": {
    "src": "/blog/img/math-behind-your-face.webp",
    "thumb": "/blog/img/math-behind-your-face-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Labelled 3D model of the bones of the human skull",
    "credit": "https://www.scientificanimations.com",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:3D_Medical_Animation_Axial_Skeleton.jpg"
  },
  "how-cnns-see-faces": {
    "src": "/blog/img/how-cnns-see-faces.webp",
    "thumb": "/blog/img/how-cnns-see-faces-sm.webp",
    "width": 1280,
    "height": 529,
    "alt": "Diagram of a convolutional neural network: convolution, pooling, flatten and classification layers",
    "credit": "Irisbox",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Convolutional_Neural_Network.png"
  },
  "what-is-facial-embedding": {
    "src": "/blog/img/what-is-facial-embedding.webp",
    "thumb": "/blog/img/what-is-facial-embedding-sm.webp",
    "width": 1280,
    "height": 828,
    "alt": "Network graph of points clustered by similarity",
    "credit": "Martin Grandjean",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SocialNetworkAnalysis.png"
  },
  "why-ai-beats-human-eye": {
    "src": "/blog/img/why-ai-beats-human-eye.webp",
    "thumb": "/blog/img/why-ai-beats-human-eye-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Macro photo of a human iris",
    "credit": "Osmo Lundell",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Iris_of_human_male.jpg"
  },
  "face-detection-vs-recognition": {
    "src": "/blog/img/face-detection-vs-recognition.webp",
    "thumb": "/blog/img/face-detection-vs-recognition-sm.webp",
    "width": 1125,
    "height": 900,
    "alt": "Illustration of a phone projecting a 3D face mesh",
    "credit": "mikemacmarketing",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Facial_Recognition22.jpg"
  },
  "how-lighting-affects-recognition": {
    "src": "/blog/img/how-lighting-affects-recognition.webp",
    "thumb": "/blog/img/how-lighting-affects-recognition-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Two softbox lights in a photo studio",
    "credit": "Katie Chan",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PhotoSEL_LS21E52_Softbox_Studio_Lighting_Kit_(2).jpg"
  },
  "inside-ai-face-matching": {
    "src": "/blog/img/inside-ai-face-matching.webp",
    "thumb": "/blog/img/inside-ai-face-matching-sm.webp",
    "width": 1280,
    "height": 850,
    "alt": "Rows of servers lit blue in a data centre",
    "credit": "BalticServers.com",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:BalticServers_data_center.jpg"
  },
  "siamese-neural-networks-explained": {
    "src": "/blog/img/siamese-neural-networks-explained.webp",
    "thumb": "/blog/img/siamese-neural-networks-explained-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Illustration of a brain drawn as circuit traces",
    "credit": "mikemacmarketing / original posted on flickr Liam Huang / clipped and posted on…",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Artificial_Neural_Network_with_Chip.png"
  },
  "why-two-networks": {
    "src": "/blog/img/why-two-networks.webp",
    "thumb": "/blog/img/why-two-networks-sm.webp",
    "width": 1280,
    "height": 591,
    "alt": "Diagram of a feed-forward neural network with weighted layers",
    "credit": "QuantuMechaniX8",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Neural_Network.svg"
  },
  "siamese-versatility": {
    "src": "/blog/img/siamese-versatility.webp",
    "thumb": "/blog/img/siamese-versatility-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "MRI scan of a human brain",
    "credit": "511KeV",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MRI_Brain_T2_Cor_(14).jpg"
  },
  "contrastive-loss-explained": {
    "src": "/blog/img/contrastive-loss-explained.webp",
    "thumb": "/blog/img/contrastive-loss-explained-sm.webp",
    "width": 1125,
    "height": 900,
    "alt": "Chart of error falling over training steps for different learning rates",
    "credit": "Kirlf",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Steepest_descent.png"
  },
  "what-is-similarity-score": {
    "src": "/blog/img/what-is-similarity-score.webp",
    "thumb": "/blog/img/what-is-similarity-score-sm.webp",
    "width": 1003,
    "height": 900,
    "alt": "Heatmap of pairwise similarity scores",
    "credit": "Chamaemelum",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ezfst.png"
  },
  "find-your-celebrity-lookalike": {
    "src": "/blog/img/find-your-celebrity-lookalike.webp",
    "thumb": "/blog/img/find-your-celebrity-lookalike-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "A star on the Hollywood Walk of Fame",
    "credit": "Dietmar Rabich",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Los_Angeles_(California,_USA),_Hollywood_Boulevard,_The_Doors_--_2012_--_5040.jpg"
  },
  "why-everyone-has-doppelganger": {
    "src": "/blog/img/why-everyone-has-doppelganger.webp",
    "thumb": "/blog/img/why-everyone-has-doppelganger-sm.webp",
    "width": 694,
    "height": 900,
    "alt": "How They Met Themselves, Dante Gabriel Rossetti's drawing of a couple meeting their doubles",
    "credit": "Dante Gabriel Rossetti",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dante_Gabriel_Rossetti_-_How_They_Met_Themselves_(1851-60).jpg"
  },
  "most-matched-celebrities": {
    "src": "/blog/img/most-matched-celebrities.webp",
    "thumb": "/blog/img/most-matched-celebrities-sm.webp",
    "width": 1280,
    "height": 848,
    "alt": "The red carpet outside the Academy Awards",
    "credit": "Alan Light",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_carpet_(2086731832)_(2).jpg"
  },
  "why-some-celebrities-matched-more": {
    "src": "/blog/img/why-some-celebrities-matched-more.webp",
    "thumb": "/blog/img/why-some-celebrities-matched-more-sm.webp",
    "width": 995,
    "height": 823,
    "alt": "Black-and-white photo of press photographers crowding a stage",
    "credit": "Brent J. Irving",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Film_cameras_and_press_photographers_at_1960_DNC_(01).jpg"
  },
  "celebrity-match-different-era": {
    "src": "/blog/img/celebrity-match-different-era.webp",
    "thumb": "/blog/img/celebrity-match-different-era-sm.webp",
    "width": 1251,
    "height": 900,
    "alt": "Vintage box camera with a flash reflector",
    "credit": "Joe Haupt from USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vintage_Imperial_Reflex_620_Duo_Lens_Film_Camera,_A_Simple_Plastic_Box_Camera_(16403678691).jpg"
  },
  "selfie-vs-passport-match": {
    "src": "/blog/img/selfie-vs-passport-match.webp",
    "thumb": "/blog/img/selfie-vs-passport-match-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Passports from several countries",
    "credit": "Horizon206",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Four_Different_Passports.jpg"
  },
  "celebrities-that-fool-ai": {
    "src": "/blog/img/celebrities-that-fool-ai.webp",
    "thumb": "/blog/img/celebrities-that-fool-ai-sm.webp",
    "width": 1183,
    "height": 900,
    "alt": "Checker shadow illusion: two squares of the same grey that look different",
    "credit": "Original: Edward H. Adelson, vectorized by Pbroks13.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Checker_shadow_illusion.svg"
  },
  "what-celebrity-match-reveals": {
    "src": "/blog/img/what-celebrity-match-reveals.webp",
    "thumb": "/blog/img/what-celebrity-match-reveals-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "A human skull on display",
    "credit": "Federigo Federighi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Human_skull_at_human_anatomy_museum_(Pisa_university).jpg"
  },
  "twins-different-celebrity": {
    "src": "/blog/img/twins-different-celebrity.webp",
    "thumb": "/blog/img/twins-different-celebrity-sm.webp",
    "width": 1280,
    "height": 852,
    "alt": "The Petronas Twin Towers seen from below",
    "credit": "Jorge Láscar from Melbourne, Australia",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Petronas_Towers,_the_tallest_twin_towers_of_the_world_(18793138848).jpg"
  },
  "science-of-you-look-like": {
    "src": "/blog/img/science-of-you-look-like.webp",
    "thumb": "/blog/img/science-of-you-look-like-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Marble and bronze portrait busts in a museum gallery",
    "credit": "No Swan So Fine",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Interior_of_the_National_Portrait_Gallery,_London,_September_2023_08.jpg"
  },
  "why-humans-bad-at-faces": {
    "src": "/blog/img/why-humans-bad-at-faces.webp",
    "thumb": "/blog/img/why-humans-bad-at-faces-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "A street crowd reflected in a kaleidoscope of mirrored panels",
    "credit": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Street_crowd_reflecting_in_the_polyhedral_mirrors_of_the_station_Tokyu_Plaza_Omotesando,_Harajuku,_Tokyo,_Japan.jpg"
  },
  "prosopagnosia": {
    "src": "/blog/img/prosopagnosia.webp",
    "thumb": "/blog/img/prosopagnosia-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "3D brain model with the fusiform gyrus highlighted in red",
    "credit": "RAZVAN V. MARINESCU",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fusiform_-_DK_ATLAS_05.png"
  },
  "pareidolia-faces-everywhere": {
    "src": "/blog/img/pareidolia-faces-everywhere.webp",
    "thumb": "/blog/img/pareidolia-faces-everywhere-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Plastic water canisters whose caps and handles look like faces",
    "credit": "TeWeBs",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Camara_de_Lobos_Pareidolia_2.JPG"
  },
  "own-race-effect": {
    "src": "/blog/img/own-race-effect.webp",
    "thumb": "/blog/img/own-race-effect-sm.webp",
    "width": 1280,
    "height": 675,
    "alt": "Aerial view of a large crowd filling a city street",
    "credit": "Eromane",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LoveFestFeb122018.jpg"
  },
  "your-own-face": {
    "src": "/blog/img/your-own-face.webp",
    "thumb": "/blog/img/your-own-face-sm.webp",
    "width": 600,
    "height": 900,
    "alt": "A person's reflection in a rain puddle on the pavement",
    "credit": "Tomascastelazo",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bicycle_reflections.jpg"
  },
  "baby-face-features": {
    "src": "/blog/img/baby-face-features.webp",
    "thumb": "/blog/img/baby-face-features-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "A puppy with big eyes holding a toy ball",
    "credit": "Funkiestfarter",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gustavo_chewing_squeaky_toy_(super_cute).jpg"
  },
  "resting-face": {
    "src": "/blog/img/resting-face.webp",
    "thumb": "/blog/img/resting-face-sm.webp",
    "width": 604,
    "height": 900,
    "alt": "Leonardo da Vinci's Mona Lisa",
    "credit": "Leonardo da Vinci",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg"
  },
  "brain-recognises-face": {
    "src": "/blog/img/brain-recognises-face.webp",
    "thumb": "/blog/img/brain-recognises-face-sm.webp",
    "width": 1123,
    "height": 900,
    "alt": "Illustration of the human brain",
    "credit": "Courtesy of NIAID Ryan Kissinger",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brain_Lateral_(NIH_BioArt_60).png"
  },
  "best-photo-celebrity-match": {
    "src": "/blog/img/best-photo-celebrity-match.webp",
    "thumb": "/blog/img/best-photo-celebrity-match-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Four smartphones laid out showing their rear cameras",
    "credit": "IPHONE MAX",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:IPhone_camera.jpeg"
  },
  "best-lighting-for-match": {
    "src": "/blog/img/best-lighting-for-match.webp",
    "thumb": "/blog/img/best-lighting-for-match-sm.webp",
    "width": 732,
    "height": 900,
    "alt": "Daylight coming through an open window",
    "credit": "Rhododendrites",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Window_in_a_cafe_in_San_Gimignano_(02182)2.jpg"
  },
  "glasses-hats-hair": {
    "src": "/blog/img/glasses-hats-hair.webp",
    "thumb": "/blog/img/glasses-hats-hair-sm.webp",
    "width": 1280,
    "height": 898,
    "alt": "Two pairs of eyeglasses",
    "credit": "Jacek Halicki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2023_Okulary_korekcyjne.jpg"
  },
  "front-vs-rear-camera": {
    "src": "/blog/img/front-vs-rear-camera.webp",
    "thumb": "/blog/img/front-vs-rear-camera-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "A smartphone camera module on its circuit board",
    "credit": "Raimond Spekking",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Huawei_Y6_(2019,_model_MRD-LX1)_-_board_1_-_rear-facing_camera_Sunny_M13N01B-47215.jpg"
  },
  "bias-in-face-recognition": {
    "src": "/blog/img/bias-in-face-recognition.webp",
    "thumb": "/blog/img/bias-in-face-recognition-sm.webp",
    "width": 1280,
    "height": 854,
    "alt": "Bronze statue of Lady Justice holding scales",
    "credit": "DP Singh Bhullar",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Close-up_of_Lady_Justice_statue_holding_scales,_symbolizing_justice_and_fairness.jpg"
  },
  "privacy-and-face-recognition": {
    "src": "/blog/img/privacy-and-face-recognition.webp",
    "thumb": "/blog/img/privacy-and-face-recognition-sm.webp",
    "width": 1280,
    "height": 890,
    "alt": "A security camera above a 'Security cameras in use' sign",
    "credit": "Myotus",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vandal_dome-style_security_camera_next_to_signage_on_exterior_of_Target_store.jpg"
  },
  "history-of-face-recognition": {
    "src": "/blog/img/history-of-face-recognition.webp",
    "thumb": "/blog/img/history-of-face-recognition-sm.webp",
    "width": 884,
    "height": 900,
    "alt": "Alphonse Bertillon's own 1891 identification card with front and profile photos",
    "credit": "Alphonse Bertillon (1853-1914)",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alphonse_Bertillon_-_fiche_anthropom%C3%A9trique_(1894).jpg"
  },
  "what-overfitting-means": {
    "src": "/blog/img/what-overfitting-means.webp",
    "thumb": "/blog/img/what-overfitting-means-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "Chart of a wiggly curve overfitting data points next to a straight-line fit",
    "credit": "Amirreza mirzaei2001",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Overfitting_regression_deg5vsdeg1.png"
  },
  "training-data-matters": {
    "src": "/blog/img/training-data-matters.webp",
    "thumb": "/blog/img/training-data-matters-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Rows of full bookshelves in a library",
    "credit": "Geonuch",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bookshelves_in_Faculty_of_Arts_Library,_Chulalongkorn_University.jpg"
  },
  "transfer-learning-explained": {
    "src": "/blog/img/transfer-learning-explained.webp",
    "thumb": "/blog/img/transfer-learning-explained-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "A sprinter crouched at the start line holding a relay baton",
    "credit": "Braden Collum bradencollum",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Relay_runner_(Unsplash).jpg"
  },
  "confidence-vs-accuracy": {
    "src": "/blog/img/confidence-vs-accuracy.webp",
    "thumb": "/blog/img/confidence-vs-accuracy-sm.webp",
    "width": 857,
    "height": 900,
    "alt": "Darts clustered on a dartboard",
    "credit": "kallerna",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tikkataulu.JPG"
  },
  "identical-twins-different-profiles": {
    "src": "/blog/img/identical-twins-different-profiles.webp",
    "thumb": "/blog/img/identical-twins-different-profiles-sm.webp",
    "width": 1192,
    "height": 897,
    "alt": "3D illustration of a DNA double helix",
    "credit": "National Human Genome Research Institute",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DNA_Double_Helix_by_NHGRI.jpg"
  },
  "expression-affects-matching": {
    "src": "/blog/img/expression-affects-matching.webp",
    "thumb": "/blog/img/expression-affects-matching-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "19th-century engraving of a face in an exaggerated expression of fear, from Duchenne's studies",
    "credit": "Guillaume Duchenne",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Expression_of_the_Emotions_Figure_20.png"
  },
  "makeup-affects-matching": {
    "src": "/blog/img/makeup-affects-matching.webp",
    "thumb": "/blog/img/makeup-affects-matching-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "Makeup brushes of different sizes on a table",
    "credit": "Kandance拍攝",
    "license": "CC BY-SA 2.0 tw",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/tw/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blush_-_A_selection_of_makeup_brushes.jpg"
  },
  "aging-face-recognition": {
    "src": "/blog/img/aging-face-recognition.webp",
    "thumb": "/blog/img/aging-face-recognition-sm.webp",
    "width": 444,
    "height": 900,
    "alt": "A wooden hourglass with sand running through",
    "credit": "User:S Sepp",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wooden_hourglass_3.jpg"
  },
  "photo-angle-celebrity-match": {
    "src": "/blog/img/photo-angle-celebrity-match.webp",
    "thumb": "/blog/img/photo-angle-celebrity-match-sm.webp",
    "width": 948,
    "height": 900,
    "alt": "A camera tripod head with adjustment handles",
    "credit": "Dmitry Makeev",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Manfrotto_tripod_heads_804RC2.jpg"
  },
  "group-photo-matching": {
    "src": "/blog/img/group-photo-matching.webp",
    "thumb": "/blog/img/group-photo-matching-sm.webp",
    "width": 1280,
    "height": 881,
    "alt": "Group photograph of the 1927 Solvay physics conference",
    "credit": "Benjamin Couprie",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Solvay_conference_1927_Version2.jpg"
  },
  "face-shape-guide": {
    "src": "/blog/img/face-shape-guide.webp",
    "thumb": "/blog/img/face-shape-guide-sm.webp",
    "width": 696,
    "height": 900,
    "alt": "Colourful geometric pattern built from triangles and hexagons",
    "credit": "Neirenz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Amper%27s_Geometric_Shape_Art_Project.jpg"
  },
  "celebrity-face-evolution": {
    "src": "/blog/img/celebrity-face-evolution.webp",
    "thumb": "/blog/img/celebrity-face-evolution-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Close-up of a reel of 35mm film",
    "credit": "Coyau",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:8_mm_Kodak_safety_film_reel_06.jpg"
  },
  "face-recognition-in-art": {
    "src": "/blog/img/face-recognition-in-art.webp",
    "thumb": "/blog/img/face-recognition-in-art-sm.webp",
    "width": 706,
    "height": 900,
    "alt": "Rembrandt's 1659 self-portrait",
    "credit": "Rembrandt",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rembrandt_self_portrait.jpg"
  },
  "golden-ratio-face": {
    "src": "/blog/img/golden-ratio-face.webp",
    "thumb": "/blog/img/golden-ratio-face-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "A spiral staircase seen from above, curling like a golden spiral",
    "credit": "Brad Hammonds",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Golden_Spiral_by_Brad_Hammonds.jpg"
  },
  "face-attractiveness-research": {
    "src": "/blog/img/face-attractiveness-research.webp",
    "thumb": "/blog/img/face-attractiveness-research-sm.webp",
    "width": 657,
    "height": 900,
    "alt": "Leonardo da Vinci's Vitruvian Man drawing",
    "credit": "Leonardo da Vinci",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vitruvian.jpg"
  },
  "face-recognition-in-dating": {
    "src": "/blog/img/face-recognition-in-dating.webp",
    "thumb": "/blog/img/face-recognition-in-dating-sm.webp",
    "width": 1125,
    "height": 900,
    "alt": "A smartphone showing its home screen on a wooden table",
    "credit": "mikemacmarketing",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Social_Media_App_Icons_On_The_Screen_of_A_Smartphone.jpg"
  },
  "face-recognition-genealogy": {
    "src": "/blog/img/face-recognition-genealogy.webp",
    "thumb": "/blog/img/face-recognition-genealogy-sm.webp",
    "width": 1280,
    "height": 758,
    "alt": "A hand-drawn historical family tree manuscript",
    "credit": "Qazi Abul Hassa, Muhammad Zia Ul Din Hakeem.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alvi_Family_Tree_Page_01.jpg"
  },
  "face-reading-pseudoscience": {
    "src": "/blog/img/face-reading-pseudoscience.webp",
    "thumb": "/blog/img/face-reading-pseudoscience-sm.webp",
    "width": 1128,
    "height": 900,
    "alt": "Ceramic phrenology heads mapped with supposed character regions",
    "credit": "Waters.Justin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phrenology_Head_Bust.jpg"
  },
  "face-recognition-mental-health": {
    "src": "/blog/img/face-recognition-mental-health.webp",
    "thumb": "/blog/img/face-recognition-mental-health-sm.webp",
    "width": 1280,
    "height": 526,
    "alt": "A still lake reflecting a green hillside",
    "credit": "Julian Herzog (Website)",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Friars%27_Crag_Derwentwater_Lake_District_2022_01.jpg"
  },
  "future-of-face-recognition": {
    "src": "/blog/img/future-of-face-recognition.webp",
    "thumb": "/blog/img/future-of-face-recognition-sm.webp",
    "width": 1280,
    "height": 852,
    "alt": "A modern building lit in blue at night",
    "credit": "PattayaPatrol",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DSC_7655_A_futuristic_rooftop_bar_glowing_with_blue_and_purple_lights_sleek_seating_and_a_stylish_lounge_area_overlooking_an_illuminated_terrace_at_night.jpg"
  },
  "face-recognition-surveillance": {
    "src": "/blog/img/face-recognition-surveillance.webp",
    "thumb": "/blog/img/face-recognition-surveillance-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "Security cameras along the ceiling of a long tunnel",
    "credit": "Gzen92",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gare_-_couloir_nord_(Strasbourg)_(2).jpg"
  },
  "face-recognition-animals": {
    "src": "/blog/img/face-recognition-animals.webp",
    "thumb": "/blog/img/face-recognition-animals-sm.webp",
    "width": 910,
    "height": 900,
    "alt": "A chimpanzee sitting and looking to the side",
    "credit": "William H. Calvin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chimpanzee_female_Twycross.jpg"
  },
  "face-symmetry-and-genetics": {
    "src": "/blog/img/face-symmetry-and-genetics.webp",
    "thumb": "/blog/img/face-symmetry-and-genetics-sm.webp",
    "width": 1280,
    "height": 721,
    "alt": "Diagram of the 23 pairs of human chromosomes",
    "credit": "National Human Genome Research Institute (NHGRI)",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Human_karyotype_diagram_showing_autosomes_and_sex_chromosomes_-_NHGRI.jpg"
  },
  "face-memory-psychology": {
    "src": "/blog/img/face-memory-psychology.webp",
    "thumb": "/blog/img/face-memory-psychology-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "3D brain model with the hippocampus highlighted in red",
    "credit": "RAZVAN V. MARINESCU",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hippocampus_-_DK_ATLAS.png"
  },
  "face-recognition-aging-brain": {
    "src": "/blog/img/face-recognition-aging-brain.webp",
    "thumb": "/blog/img/face-recognition-aging-brain-sm.webp",
    "width": 900,
    "height": 900,
    "alt": "Side-view MRI scan of a human head and brain",
    "credit": "511KeV",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MRI_Brain_T1_Sag_(13).jpg"
  },
  "baby-face-recognition-development": {
    "src": "/blog/img/baby-face-recognition-development.webp",
    "thumb": "/blog/img/baby-face-recognition-development-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "Colourful baby teething toys on a wooden floor",
    "credit": "Zeromonk",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Plastic_baby_rattle_toy.jpg"
  },
  "culture-and-face-recognition": {
    "src": "/blog/img/culture-and-face-recognition.webp",
    "thumb": "/blog/img/culture-and-face-recognition-sm.webp",
    "width": 634,
    "height": 900,
    "alt": "A carved and painted traditional Sri Lankan mask",
    "credit": "Henda Hewa Tharaka Nirmal",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:(Maru_Rakshaya)_Traditional_masks_of_Ambalangoda,_Sri_Lanka_-_Tharaka_Nirmal_Photography.png"
  },
  "face-recognition-with-mask": {
    "src": "/blog/img/face-recognition-with-mask.webp",
    "thumb": "/blog/img/face-recognition-with-mask-sm.webp",
    "width": 1200,
    "height": 900,
    "alt": "A blue disposable surgical mask",
    "credit": "AlexChirkin",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_surgical_mask_(2017).jpg"
  },
  "weight-change-and-matching": {
    "src": "/blog/img/weight-change-and-matching.webp",
    "thumb": "/blog/img/weight-change-and-matching-sm.webp",
    "width": 1209,
    "height": 900,
    "alt": "An ornate antique brass balance scale",
    "credit": "Nikodem Nijaki",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Balance_scale_IMGP9722.jpg"
  },
  "hair-color-affects-matching": {
    "src": "/blog/img/hair-color-affects-matching.webp",
    "thumb": "/blog/img/hair-color-affects-matching-sm.webp",
    "width": 676,
    "height": 900,
    "alt": "Blonde hair being coloured with purple dye",
    "credit": "WhatamIdoing",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dyeing_hair_purple.png"
  },
  "beard-affects-matching": {
    "src": "/blog/img/beard-affects-matching.webp",
    "thumb": "/blog/img/beard-affects-matching-sm.webp",
    "width": 656,
    "height": 900,
    "alt": "A safety razor and shaving brush on a stand",
    "credit": "Evan-Amos",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shaving-Set.jpg"
  },
  "ollie-how-it-works": {
    "src": "/blog/img/ollie-how-it-works.webp",
    "thumb": "/blog/img/ollie-how-it-works-sm.webp",
    "width": 1248,
    "height": 630,
    "alt": "A graphics card, the kind of chip used to run neural networks",
    "credit": "Asim18 at English Wikipedia",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gpu-connections.png"
  },
  "improving-ollie-results": {
    "src": "/blog/img/improving-ollie-results.webp",
    "thumb": "/blog/img/improving-ollie-results-sm.webp",
    "width": 604,
    "height": 900,
    "alt": "A softbox light set up in a small photo studio",
    "credit": "THOR",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Still_life_photography_studio_setup_with_softboxes,_by_geishaboy500.jpg"
  },
  "understanding-your-results": {
    "src": "/blog/img/understanding-your-results.webp",
    "thumb": "/blog/img/understanding-your-results-sm.webp",
    "width": 1280,
    "height": 512,
    "alt": "Colourful bar chart",
    "credit": "allixpeeke",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:United_States_presidential_election_ordinal_results_bar_graph_(Expanded).png"
  },
  "cross-age-celebrity-match": {
    "src": "/blog/img/cross-age-celebrity-match.webp",
    "thumb": "/blog/img/cross-age-celebrity-match-sm.webp",
    "width": 673,
    "height": 900,
    "alt": "A 19th-century family portrait photograph",
    "credit": "Conrad L'Allemand",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Family_George_V_of_Hanover.jpg"
  },
  "vggface2-explained": {
    "src": "/blog/img/vggface2-explained.webp",
    "thumb": "/blog/img/vggface2-explained-sm.webp",
    "width": 1280,
    "height": 786,
    "alt": "Archive binders full of photo slides and negatives",
    "credit": "Silvia Florindi",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Archivio_Fotografico_IIPP.jpg"
  },
  "resnet-face-recognition": {
    "src": "/blog/img/resnet-face-recognition.webp",
    "thumb": "/blog/img/resnet-face-recognition-sm.webp",
    "width": 1280,
    "height": 693,
    "alt": "Diagram of a residual block: two layers plus an identity shortcut, x + F(x)",
    "credit": "LunarLullaby",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ResBlock.png"
  },
  "arcface-explained": {
    "src": "/blog/img/arcface-explained.webp",
    "thumb": "/blog/img/arcface-explained-sm.webp",
    "width": 1152,
    "height": 900,
    "alt": "3D plot of a unit sphere with an arc drawn across its surface",
    "credit": "BagLuke",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sphere_with_an_opaque_set_of_type_(1,_2)_(figure_B).png"
  },
  "face-recognition-benchmark": {
    "src": "/blog/img/face-recognition-benchmark.webp",
    "thumb": "/blog/img/face-recognition-benchmark-sm.webp",
    "width": 729,
    "height": 900,
    "alt": "A mechanical stopwatch",
    "credit": "Stefan (Diskussion). Original uploader was StefanPohl at German Wikipedia",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stoppuhr_hanhart.jpg"
  },
  "face-hashing-privacy": {
    "src": "/blog/img/face-hashing-privacy.webp",
    "thumb": "/blog/img/face-hashing-privacy-sm.webp",
    "width": 989,
    "height": 900,
    "alt": "A brass padlock with its keys",
    "credit": "Trougnouf",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Solex_99_30_padlock_with_keys_(DSCF2659).jpg"
  },
  "face-spoof-detection": {
    "src": "/blog/img/face-spoof-detection.webp",
    "thumb": "/blog/img/face-spoof-detection-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "A wall of Venetian carnival masks",
    "credit": "Marek Ślusarczyk (Tupungato) Photo portfolio",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:23_Souvenir_from_Venice,_Italy_-_small_Venetian_carnival_mask_magnet_in_gift_shop.jpg"
  },
  "face-recognition-performance-tricks": {
    "src": "/blog/img/face-recognition-performance-tricks.webp",
    "thumb": "/blog/img/face-recognition-performance-tricks-sm.webp",
    "width": 1280,
    "height": 853,
    "alt": "A network switch in a server rack with cables plugged in",
    "credit": "Helpameout",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wikimedia_Servers-0001_42.jpg"
  },
  "symmetrical-faces": {
    "src": "/blog/img/symmetrical-faces.webp",
    "thumb": "/blog/img/symmetrical-faces-sm.webp",
    "width": 1280,
    "height": 720,
    "alt": "A perfectly mirror-symmetric butterfly graphic",
    "credit": "Silharstak",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PHOBIA_Symbol.png"
  },
  "uncanny-valley": {
    "src": "/blog/img/uncanny-valley.webp",
    "thumb": "/blog/img/uncanny-valley-sm.webp",
    "width": 600,
    "height": 900,
    "alt": "Close-up of a humanoid robot with a human-like face",
    "credit": "Sven Volkens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Humanoider-Roboter-DASA.JPG"
  },
  "accuracy-across-demographics": {
    "src": "/blog/img/accuracy-across-demographics.webp",
    "thumb": "/blog/img/accuracy-across-demographics-sm.webp",
    "width": 1280,
    "height": 851,
    "alt": "A world globe turned to show Africa and Asia",
    "credit": "Wendy Cope",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Globe_with_yellow_background_1.jpg"
  },
  "celebrity-doppelgangers-throughout-history": {
    "src": "/blog/img/celebrity-doppelgangers-throughout-history.webp",
    "thumb": "/blog/img/celebrity-doppelgangers-throughout-history-sm.webp",
    "width": 684,
    "height": 900,
    "alt": "19th-century illustration of the identical Dromio twins from Shakespeare's Comedy of Errors",
    "credit": "J. Coghlan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Comedy_of_errors_IV.i.jpg"
  },
  "celebrity-resemblance-and-self-image": {
    "src": "/blog/img/celebrity-resemblance-and-self-image.webp",
    "thumb": "/blog/img/celebrity-resemblance-and-self-image-sm.webp",
    "width": 367,
    "height": 900,
    "alt": "An antique framed mirror hanging on a wall",
    "credit": "Napier Andrews",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Antique_Trumeau_reproduction.jpg"
  },
  "face-recognition-in-medicine": {
    "src": "/blog/img/face-recognition-in-medicine.webp",
    "thumb": "/blog/img/face-recognition-in-medicine-sm.webp",
    "width": 1161,
    "height": 900,
    "alt": "Historical photo of a scientist at a microscope in a laboratory",
    "credit": "Harris & Ewing, photographer",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Man_using_microscope_in_laboratory_LCCN2016882745.jpg"
  },
  "celebrity-database-how-built": {
    "src": "/blog/img/celebrity-database-how-built.webp",
    "thumb": "/blog/img/celebrity-database-how-built-sm.webp",
    "width": 1064,
    "height": 900,
    "alt": "An open drawer in a wooden library card catalogue",
    "credit": "Dr. Marcus Gossler",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Schlagwortkatalog.jpg"
  },
  "what-makes-a-face-memorable": {
    "src": "/blog/img/what-makes-a-face-memorable.webp",
    "thumb": "/blog/img/what-makes-a-face-memorable-sm.webp",
    "width": 939,
    "height": 900,
    "alt": "A 16th-century Holbein portrait miniature of a man in a black cap",
    "credit": "Lucas Horenbout",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Portrait_miniature_of_a_gentleman,_possibly_Charles_Brandon,_Duke_of_Suffolk.jpg"
  }
}
